### PR TITLE
Feature test

### PR DESCRIPTION
**Pull request by m4github**

### CODE REVIEW

**Comment by alirezaarzehgar** [comment]
What is this PR ? Idk what you modified in this branch and what you added to it. please explain it on description.

**Comment by m4github** [comment]
> What is this PR ? Idk what you modified in this branch and what you added to it. please explain it on description.

listener_test.c added.

**Comment by alirezaarzehgar** [comment]
> > What is this PR ? Idk what you modified in this branch and what you added to it. please explain it on description.
> 
> listener_test.c added.

please edit description and put your own explanation there.

**Comment by m4github** [comment]
@alirezaarzehgar 
aqa im telling you that i added a new src code for inline functions test that are in listener.h SO just check it and help to make it better -_-

**Comment by alirezaarzehgar** [comment]
> @alirezaarzehgar aqa im telling you that i added a new src code for inline functions test that are in listener.h SO just check it and help to make it better -_-

Pull requests should be acceptable.
I can't merge wrong PR on our repository and everything should be ok .

make it better.

**Pull request closed without merging**
